[package]
name = "bar"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
smol = "2.0.2"
compositor_bridge = { path = "./compositor_bridge" }
iced = { version = "0.14.0", features = ["smol", "lazy", "image"] }
iced_layershell = { version = "0.18.1", features = ["unconditional-rendering"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
chrono = "0.4.45"
battery = "0.7.8"
either = "1.16.0"
rustsni = "0.2.2"
native-theme = "0.5.7"
native-theme-iced = "0.5.7"
async-signal = "0.2.14"
font-kit = "0.14.3"
